# 모든 서비스의 공통 설정 -> 중복 제거 
# localhost ver. 
server:
    # eureka server에 의해서 임의의 포트번호가 할당됨
    port: 0

# eureka client 설정 
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka

spring:
    rabbitmq:
        host: localhost
        port: 5672
        username: guest
        password: guest 

    datasource: # 연결할 DB 설정 
        driver-class-name: org.mariadb.jdbc.Driver  # MariaDB와 연결할 수 있는 드라이버 클래스 
        url: jdbc:mariadb://localhost:3306/inspire # 로컬 DB (외부 DB와 연결하고 싶다면 EndPoint 연결)
        username: root 
        password: 1215
    jpa:
        hibernate: 
            # create(-> 서버 기동 시점에 생성된 entity에 매핑되는 테이블 자동 생성), create-drop, update, none
            ddl-auto:  create
        # 콘솔출력
        show-sql: true     
        properties:
            hibernate:
                # h2
                # dialect: org.hibernate.dialect.H2Dialect
                # mariadb
                dialect: org.hibernate.dialect.MariaDBDialect
                format_sql: true

    #redis
    data:
        redis:
            host: localhost
            port: 6379
            password: 
            timeout: 6000ms
    
    cloud:
        bus:
            enabled: true